# Generated by Django 4.0.5 on 2022-08-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_rename_policy_effective_date_post_policy_effective_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='industry',
            field=models.CharField(choices=[('Banking', 'Banking'), ('Finance', 'Finance'), ('Tech', 'Tech'), ('Entertainment', 'Entertainment'), ('Art', 'Art'), ('E-Commerce', 'E-Commerce')], max_length=13),
        ),
    ]
