# Generated by Django 4.0.5 on 2022-08-08 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_post_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Policy_Effective_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
