# Generated by Django 4.0.5 on 2022-08-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_post_address_alter_post_policy_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Phone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='poli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='industry',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Finance', 'Finance'), ('Tech', 'Tech'), ('Entertainment', 'Entertainment'), ('Art', 'Art'), ('E-Commerce', 'E-Commerce')], max_length=13),
        ),
    ]
